name = "MoM_Kernels"
uuid = "831fc53b-0fa6-4fbb-adc4-fa1e0b19763e"
authors = ["deltaeecs <1225385871@qq.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
